// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzhE3I00GizQ2Y8QLedwrdlidCAZ_PA8',
    appId: '1:498976315854:web:ceb582ea2fd2288e84339f',
    messagingSenderId: '498976315854',
    projectId: 'musijournal-c3334',
    authDomain: 'musijournal-c3334.firebaseapp.com',
    storageBucket: 'musijournal-c3334.firebasestorage.app',
    measurementId: 'G-7KYYL5YSXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7kK-VZzhqHZv0c7v_YGNRZcc9wXQPBeU',
    appId: '1:498976315854:android:2fd27ebf0b2c13ca84339f',
    messagingSenderId: '498976315854',
    projectId: 'musijournal-c3334',
    storageBucket: 'musijournal-c3334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtW92dTEIqHWHq4gyuhhIrZ6xWSxEVtdo',
    appId: '1:498976315854:ios:7b412a550be1653184339f',
    messagingSenderId: '498976315854',
    projectId: 'musijournal-c3334',
    storageBucket: 'musijournal-c3334.firebasestorage.app',
    iosBundleId: 'com.lucashu.musictherapytrackerWindows',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtW92dTEIqHWHq4gyuhhIrZ6xWSxEVtdo',
    appId: '1:498976315854:ios:7b412a550be1653184339f',
    messagingSenderId: '498976315854',
    projectId: 'musijournal-c3334',
    storageBucket: 'musijournal-c3334.firebasestorage.app',
    iosBundleId: 'com.lucashu.musictherapytrackerWindows',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzhE3I00GizQ2Y8QLedwrdlidCAZ_PA8',
    appId: '1:498976315854:web:15e3c146d5b3bfe584339f',
    messagingSenderId: '498976315854',
    projectId: 'musijournal-c3334',
    authDomain: 'musijournal-c3334.firebaseapp.com',
    storageBucket: 'musijournal-c3334.firebasestorage.app',
    measurementId: 'G-W7J14WZWD2',
  );

}